
spring:
  #数据源
  datasource:
    #driver-class-name: oracle.jdbc.OracleDriver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:oracle:thin:@192.1.1.13:1521:orcl
    username: system
    password: manager
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: om.hd.imms.entity
#mybatis-plus:
  # xml地址
 # mapper-locations: classpath*:mapper/ds1/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  #type-aliases-package: om.hd.imms.entity
  #configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8090
