
spring:
  profiles:
    active: production
  #数据源
  datasource:
    ds1:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@192.1.1.13:1521:orcl
      username: system
      password: manager
    ds2:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@192.1.2.20:1521:orcl
      username: mhis
      password: mhis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  # xml地址
  mapper-locations: classpath*:mapper/ds1/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: om.hd.imms.entity.performance
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8090
